
name: workflow learn first

on:
  push:
    branches:
      - main

jobs:
  job-one:   # 👈 job name added here
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: say something
        run: echo "This is job one done"

